// // // // What is javascript.
// // // A high-level object-oriented and scriptive programming language
// // // uesd by web browsers for creating interactive effects on the web application.


// // //  Features 
// // 1.Dynamically typed language.
// // 2.Fully intigrated with HTML and CSS.
// // 3.Event Driven Programming.
// // 4.Easly used in server side(backend) and client side(frontend)
// // 5.By default it is single threaded language but can be used in multithreading
// // 6.Top libraries of js : React.js Express.js Angular.js vue.js Jquery tec.


// // Applcation of javascript
// 1.Devoloping web apps like : e-commerce , chat system , social media platform
// 2.Management system.

// Variables:
// Variable is a memory named location where data stored.
// Variable is like a container used to store data.
// Rules: 
// 1.Cannot startwith number or symbol.
// 2.Cannot contain white sapces number or symbol.
// 3.Variable can mix character a-z.

// // Three keyword used to declare variable in javascript
// let a; // declared
// a=200;
// a=400;

// let a = 600;

// var b=200;
// var b=300;
// var b=400;


// const pi=390;


// DATA TYPE.....
// DATA TYPE MEANS WHAT TYPE OF DATA STORED IN  A VARIABLE.
// NUMBER
// STRING
// BOOLEAN
// NULL
// .UNDEFINED
// SYMBOL
// BIGNIT

// ADDITION

// Console.log("-------addition-------")
// var n1=100.29;
// var n2=200;
// var res=n1+n2;
// var id=document.getElementById('btn')
// id.innerHTML="THE SUM IS" +res;

// console.log(res)
// console.log("value of n1:",n1,"value of n2:",n2,"Sum=",res)
// console.log('value of n1:${n1} value of n2:${n2} Sum:${res}')

