// DATA TYPE.....
// DATA TYPE MEANS WHAT TYPE OF DATA STORED IN  A VARIABLE.
// NUMBER
// STRING
// BOOLEAN
// NULL
// .UNDEFINED
// SYMBOL
// BIGNIT

// ADDITION

// Console.log("-------addition-------")
// var n1=100.29;
// var n2=200;
// var res=n1+n2;
// var id=document.getElementById('btn')
// id.innerHTML="THE SUM IS" +res;

// console.log(res)
// console.log("value of n1:",n1,"value of n2:",n2,"Sum=",res)
// console.log('value of n1:${n1} value of n2:${n2} Sum:${res}')

